terminal_example: 
  name: "terminal"
  icon: "icon_terminal_example.svg"
  tooltip: "Launch terminal"
  # use here $name to get value from app.constants 
  action: "$terminal"
  need_sudo: false
  style_classes: []

