

app:
  name: "Vela"

  modules: "../config/modules/"
  sqripts: "../config/scripts/"
  static: "../config/static/"

  constants:
    # define four terminal
    terminal: "kitty"


bars:
  left: true
  right: true
  top: true
  bottom: true

window:
  width: 600
  height: 400
  rows: 4
  columns: 5
  # arifmetic centre of chosed modules matching to centr_pos
  centring_obj: ["main", "left"]
  # centre of window - 0, 0, first number increace to move right, second to move up 
  centr_pos: [0, 0] 

bar_left:
  width: 50

bar_right:
  width: 50

bar_top:
  height: 50

bar_bottom:
  height: 50

modules:
  main:
    terminal_example: 
      row: 1
      column: 1
      path: "terminal_example.yaml"

    script_example:
      row: 1
      column: 2
      path: "script_example.yaml"
  left:
    # elements on left bar
  right:
    # elements on right bar
  top:
    # elements on top bar
  bottom: 
    # elements on bottom bar
