

app:
  # relative path from root of proiject
  modules: "config/modules/"
  scripts: "config/scripts/"
  static: "config/static/"

  # support rgb and rgba format
  --color-focus-border-1: "rgba(42, 206, 201, 1)"
  --color-focus-border-2: "rgba(57, 212, 109, 1)"
  # time in ms
  --focus-border-fade-duration: 100
  # border radius in px
  --focus-border-radius: 10

  constants:
    # define constants you can use in "action" of modules like $constant (exept "script")
    terminal: "kitty"


bars:
  left: true
  right: false
  top: true
  bottom: false

window:
  width: 600
  height: 400
  # size of icon of module 
  size: &size 72
  rows: 4
  columns: 5
  # arifmetic centre of chosed modules matching to centr_pos
  centring_obj: ["main", "left"]
  # centre of window - 0, 0, first number increace to move right, second to move up 
  centr_pos: [0, 0] 

bar_left:
  size: 50
  # size will autoexpand if modules will demand it
  width: 50
  rows: 4

bar_right:
  size: *size
  width: 50
  rows: 4

bar_top:
  size: 40
  height: 50
  columns: 6

bar_bottom:
  size: *size
  height: 50
  columns: 6

modules:
  # position in 0 indexation 
  main:
    terminal_example: 
      row: 0
      column: 0
      # relative path from config/modules or absolute path
      path: "terminal_example.yaml"

    script_example:
      row: 1
      column: 4
      path: "script_example.yaml"
  left:
    # elements on left bar
    terminal_example: 
      row: 2
      column: 0
      path: "terminal_example.yaml"
  right:
    # elements on right bar
  top:
    # elements on top bar
    terminal_example: 
      row: 0
      column: 3
      path: "terminal_example.yaml"
  bottom: 
    # elements on bottom bar
